/**
 * DeployPlan — the central type that drives v2 deploy strategy selection.
 *
 * One template scaffolded by TM Code (or one project imported from elsewhere
 * and detected by runtimeDetector) maps to exactly one DeployPlan kind. The
 * kind tells deployService which strategy module to invoke (static-spa,
 * cf-ssr, workers-container, composite — see PLAN-DEPLOY-V2 §4).
 *
 * Persisted at project root as `.toquemedia-deploy.json` once the user has
 * accepted the detected plan. Separate from `.toquemedia-template` (which
 * records the scaffold provenance) so manual overrides and re-runs survive
 * the same way as for the template manifest.
 */
import { invoke } from '@tauri-apps/api/core'
import { logger } from '../../utils/logger'

export const DEPLOY_FILE_NAME = '.toquemedia-deploy.json'

// ── SSR adapters supported by cf-ssr ─────────────────────────
export type SsrAdapter = 'next-on-pages' | 'sveltekit' | 'nuxt' | 'astro'

// ── Container runtimes supported by workers-container ────────
export type ContainerRuntime =
  | { lang: 'node'; version: '20' | '22' }
  | { lang: 'python'; version: '3.12' }
  | { lang: 'go'; version: '1.22' }
  | { lang: 'rust'; edition: '2021' }
  | { lang: 'ruby' | 'java'; version: string }

// ── Plan kinds ───────────────────────────────────────────────

/**
 * Pure static SPA — Vite/Angular/Astro-static builds to a flat output dir.
 * Deploys to Cloudflare R2 + Workers Static Assets with client-side routing
 * fallback to spaFallback (default 'index.html').
 */
export interface StaticSpaPlan {
  kind: 'static-spa'
  /** Path relative to project root, e.g. 'dist' or 'dist/my-app/browser'. */
  outputDir: string
  /** File served for unmatched routes (SPA routing). Default 'index.html'. */
  spaFallback?: string
}

/**
 * Framework-SSR via a Cloudflare adapter. The framework's own build produces
 * both static assets and a Worker entry that handles SSR requests.
 */
export interface CfSsrPlan {
  kind: 'cf-ssr'
  adapter: SsrAdapter
  /** Static assets dir (rendered HTML, hashed JS/CSS). */
  assetsDir: string
  /** Path to the framework-emitted Worker entry. */
  workerEntry: string
}

/**
 * User-owned backend running in a Cloudflare Container. Worker wrapper is
 * generated by `provision_deploy` and routes /api/* to the container fetch
 * binding; the container itself is the user's code unchanged.
 */
export interface WorkersContainerPlan {
  kind: 'workers-container'
  runtime: ContainerRuntime
  /** Port the user's server listens on inside the container. */
  port: number
  /** Names of env vars the container expects at runtime (values resolved at
   *  deploy time from the project's .env). */
  envVars: string[]
}

/**
 * Frontend + backend in a monorepo. Worker router proxies apiPrefix to the
 * container, serves the rest from R2 / static assets.
 */
export interface CompositePlan {
  kind: 'composite'
  frontend: StaticSpaPlan | CfSsrPlan
  backend: WorkersContainerPlan
  /** URL prefix routed to the backend container. Default '/api'. */
  apiPrefix: string
}

export type DeployPlan = StaticSpaPlan | CfSsrPlan | WorkersContainerPlan | CompositePlan

// ── Persist / load ───────────────────────────────────────────

/**
 * Read `.toquemedia-deploy.json` from the project root. Returns null if the
 * file is absent (first-time deploy) or unparsable (corrupted — we treat it
 * as absent rather than crash the modal).
 */
export async function loadDeployPlan(projectPath: string): Promise<DeployPlan | null> {
  try {
    const raw = await invoke<string>('read_file', { path: `${projectPath}/${DEPLOY_FILE_NAME}` })
    const parsed = JSON.parse(raw) as DeployPlan
    if (!parsed || typeof parsed !== 'object' || !('kind' in parsed)) {
      logger.warn('deploy-plan', `Invalid ${DEPLOY_FILE_NAME} at ${projectPath} — ignoring`)
      return null
    }
    return parsed
  } catch {
    return null
  }
}

/** Atomically write `.toquemedia-deploy.json` at the project root. */
export async function saveDeployPlan(projectPath: string, plan: DeployPlan): Promise<void> {
  await invoke('write_file', {
    path: `${projectPath}/${DEPLOY_FILE_NAME}`,
    content: JSON.stringify(plan, null, 2) + '\n',
  })
}
