import { invoke } from '@tauri-apps/api/core'
import { useChatStore } from '../../../stores/chatStore'
import { runAgentWithCallbacks } from '../agentRunner'

export async function executeInit(_args: string, projectPath: string): Promise<void> {
  const chatStore = useChatStore.getState()

  // Check if TMS.md already exists
  const tmsPath = `${projectPath}/TMS.md`
  let existingTms: string | null = null

  try {
    existingTms = await invoke<string>('read_file', { path: tmsPath })
  } catch {
    // Doesn't exist — normal
  }

  if (existingTms) {
    chatStore.addSystemMessage(
      'TMS.md already exists. The agent will update it with fresh analysis.'
    )
  } else {
    chatStore.addSystemMessage(
      'Analyzing project to generate TMS.md...'
    )
  }

  const initPrompt = buildInitPrompt(projectPath, existingTms)

  await runAgentWithCallbacks(initPrompt, {
    addUserMessage: true,
    userMessageText: '/init',
  })
}

function buildInitPrompt(projectPath: string, existingTms: string | null): string {
  if (existingTms) {
    return `Analyze this project and UPDATE the existing TMS.md file at ${projectPath}/TMS.md.

The current TMS.md is already in your context (see <project_memory>). Read it with read_file to get the full content if needed.

Do the following:
1. Re-analyze the project structure, dependencies, and configuration
2. Update the "Project Analysis" section with any changes
3. PRESERVE the "Memory" section — do NOT overwrite milestones, decisions, or pending tasks
4. PRESERVE the "Custom Instructions" section
5. Write the updated TMS.md using write_file

Use tools to read the project files before updating.
Do NOT include or echo the TMS.md content in your text response. Just write the file and confirm briefly what was updated.`
  }

  return `Analyze this project and create a TMS.md file at ${projectPath}/TMS.md.

Use your tools to explore the project:
1. List the directory structure (2 levels deep)
2. Read package.json, tsconfig.json, Cargo.toml, go.mod, requirements.txt — whichever exist
3. Read README.md if it exists
4. Check for existing config files (.eslintrc, .prettierrc, vitest.config, jest.config, etc.)
5. Check for CI/CD configs (.github/workflows/, Dockerfile, etc.)

Then generate TMS.md with this EXACT structure:

\`\`\`markdown
# TMS — Project Memory

> Auto-generated by TM Code. Last updated: {current date}
> This file is read by the AI agent at the start of each session.

---

## Project Analysis

### Overview
- **Name:** {from package.json or folder name}
- **Framework:** {React, Vue, Angular, Next.js, Go, Python, etc.}
- **Language:** {TypeScript, JavaScript, Go, Python, Rust, etc.}
- **Package Manager:** {npm, yarn, pnpm, go modules, pip}
- **Monorepo:** {yes/no}

### Commands
- **Install:** {npm install, go mod download, pip install -r requirements.txt, etc.}
- **Dev:** {npm run dev, go run main.go, python main.py, etc.}
- **Build:** {npm run build, go build, etc.}
- **Test:** {npm test, go test ./..., pytest, etc.}
- **Lint:** {npm run lint, golangci-lint run, etc.}

### Structure
{key directories and their purpose, 2-3 lines each}

### Conventions Detected
{naming patterns, file organization, import style, etc. — inferred from existing code}

### Dependencies (Key)
{list top 5-10 most important dependencies with their purpose}

---

## Memory

### Milestones
{empty — will be filled as work progresses}

### Decisions
{empty — will be filled as architectural decisions are made}

### Pending Tasks
{empty — will be filled as tasks are identified}

---

## Custom Instructions

{empty — developer can add custom rules here}
Add your project-specific instructions below. These will guide the AI agent.

\`\`\`

IMPORTANT:
- Be accurate — only write what you can confirm from the files
- If a command doesn't exist (no test script, no lint script), write "not configured"
- The Memory section MUST start empty
- The Custom Instructions section MUST start with the placeholder text
- Write the file using the write_file tool
- Do NOT include or echo the TMS.md content in your text response. Just write the file and confirm briefly what was analyzed.`
}
