import { useChatStore } from '../../../stores/chatStore'
import { useAgentStore } from '../../../stores/agentStore'
import { runAgentWithCallbacks } from '../agentRunner'

export async function executePlan(args: string, projectPath: string): Promise<void> {
  const chatStore = useChatStore.getState()

  if (!args.trim()) {
    chatStore.addSystemMessage(
      'Usage: /plan <description of what you want to build>\n\n' +
      'Example: /plan user authentication with email, Google login, and role-based access'
    )
    return
  }

  // Run the architect agent — it analyzes the project and writes PLAN.md
  await runAgentWithCallbacks(buildArchitectPrompt(args, projectPath), {
    addUserMessage: true,
    userMessageText: `/plan ${args}`,
  })

  // Only show approval card if the agent didn't error out
  if (useAgentStore.getState().status !== 'error') {
    chatStore.addCardMessage('plan_approval', projectPath)
  }
}

export async function handlePlanApprove(projectPath: string): Promise<void> {
  const chatStore = useChatStore.getState()

  chatStore.addSystemMessage('Plan approved. Generating development task list...')

  // Generate TODO.md from the approved plan
  await runAgentWithCallbacks(buildTodoPrompt(projectPath), {
    addUserMessage: true,
    userMessageText: 'Generate task list from approved plan',
  })

  // Only show todo card if the agent didn't error out
  if (useAgentStore.getState().status !== 'error') {
    chatStore.addCardMessage('todo_list', projectPath)
  }
}

export function handlePlanRequestChanges(): void {
  const chatStore = useChatStore.getState()
  chatStore.addSystemMessage(
    'What changes would you like? Describe in the chat and the architect will revise the plan.'
  )
}

export function handlePlanReject(): void {
  const chatStore = useChatStore.getState()
  chatStore.addSystemMessage('Plan rejected. You can start a new plan with /plan.')
}

export async function handleStartExecution(projectPath: string): Promise<void> {
  const chatStore = useChatStore.getState()

  chatStore.addSystemMessage('Starting plan execution...')

  const executionPrompt = `Read the TODO.md at ${projectPath}/TODO.md and start executing the tasks IN ORDER.

For each task:
1. Announce which task you're starting
2. Implement it completely
3. Mark it as done in TODO.md by changing "- [ ]" to "- [x]"
4. Move to the next task

If you encounter a problem:
- Try to solve it
- If you can't, explain the issue and move to the next task
- Add the blocked task to the "Pending Tasks" section of TMS.md

Update TMS.md Memory section as you complete milestones.

Start with the first uncompleted task.`

  await runAgentWithCallbacks(executionPrompt, {
    addUserMessage: true,
    userMessageText: 'Start executing the development plan',
  })
}

function buildArchitectPrompt(userIdea: string, projectPath: string): string {
  return `You are acting as a SOFTWARE ARCHITECT. The user wants to build something and needs a complete plan before any code is written.

## User's Idea
"${userIdea}"

## Your Task

Analyze the existing project (read TMS.md if it exists, package.json, project structure) and create a comprehensive development plan.

Write a file called PLAN.md at ${projectPath}/PLAN.md with this EXACT structure:

\`\`\`markdown
# Development Plan

> Generated by TM Code Architect
> Date: {current date}
> Status: PENDING APPROVAL

## 1. Overview

### What We're Building
{2-3 sentences describing the feature/system in concrete terms}

### Goals
{3-5 bullet points of what this achieves for the user}

### Out of Scope
{what this plan explicitly does NOT include}

---

## 2. Architecture

### System Design
{high-level architecture — how components connect}
{use ASCII diagrams where helpful}

### Data Model
{entities, relationships, key fields}

### API / Routes
{endpoints or routes needed, method, purpose}

### State Management
{what state is needed, where it lives, how it flows}

---

## 3. Functional Specs

{for each feature/screen, describe:}

### 3.1 {Feature Name}
- **What it does:** {user-facing behavior}
- **Inputs:** {what the user provides}
- **Outputs:** {what the user sees/gets}
- **Business Rules:** {validation, constraints, edge cases}
- **Error States:** {what can go wrong and how to handle it}

---

## 4. Visual Specs

{for each screen/view, describe the layout:}

### 4.1 {Screen Name}
- **Layout:** {describe the layout structure}
- **Components:** {list UI components needed}
- **Interactions:** {click, hover, drag, transitions}

{use ASCII wireframes where helpful}

---

## 5. Technical Decisions

| Decision | Choice | Rationale |
|----------|--------|-----------|
| {what} | {chosen option} | {why} |

---

## 6. File Structure

{new files and directories to create}

---

## 7. Complexity Estimate

| Phase | Tasks | Complexity |
|-------|-------|------------|
| {phase} | {count} | {low/medium/high} |

**Total estimated tasks:** {number}
**Estimated complexity:** {low/medium/high}
\`\`\`

## IMPORTANT INSTRUCTIONS:

1. READ the project first — understand the existing stack, conventions, and structure
2. If TMS.md exists, read it and follow its conventions
3. Be SPECIFIC — no vague descriptions. Every spec should be implementable.
4. Use ASCII wireframes for visual specs — they're more useful than words
5. Consider the EXISTING code — don't propose changes that conflict with what's already built
6. Data models should include field names and types
7. API routes should include method, path, request/response shape
8. The plan must be COMPLETE — a developer should be able to implement from this alone
9. Write the plan to PLAN.md using write_file
10. After writing PLAN.md, give a brief summary in the chat (3-5 sentences of what you planned)`
}

function buildTodoPrompt(projectPath: string): string {
  return `Read the approved PLAN.md at ${projectPath}/PLAN.md and generate a detailed development task list.

Write a file called TODO.md at ${projectPath}/TODO.md with this structure:

\`\`\`markdown
# Development Tasks

> Generated from PLAN.md by TM Code
> Date: {current date}
> Status: 0/{total} tasks completed

---

## Phase 1 — {Phase Name} (Foundation)

- [ ] **Task 1.1:** {specific, actionable task}
  - Files: {files to create/modify}
  - Depends on: none

- [ ] **Task 1.2:** {specific, actionable task}
  - Files: {files to create/modify}
  - Depends on: Task 1.1

## Phase 2 — {Phase Name} (Core Features)

- [ ] **Task 2.1:** {specific, actionable task}
  - Files: {files to create/modify}
  - Depends on: Phase 1

## Phase 3 — {Phase Name} (Polish & Integration)

- [ ] **Task 3.1:** ...

---

## Summary

| Phase | Tasks | Depends On |
|-------|-------|------------|
| Phase 1 — {name} | {count} | — |
| Phase 2 — {name} | {count} | Phase 1 |
| Phase 3 — {name} | {count} | Phase 2 |

**Total: {count} tasks**
\`\`\`

## INSTRUCTIONS:

1. Read PLAN.md first
2. Break each feature/spec into small, atomic tasks (1-2 hours each max)
3. Order tasks by dependency — never reference a task that hasn't been done yet
4. Group into phases (foundation -> core -> polish)
5. Each task must specify which files it creates or modifies
6. Each task must be concrete enough that a developer can start immediately
7. Include setup tasks (install deps, create directories, config files)
8. Include testing tasks where appropriate
9. Write to TODO.md using write_file
10. Present a summary in the chat`
}
