/**
 * Disposable / temporary email domain blocklist. Curated subset of the public
 * list at github.com/disposable-email-domains/disposable-email-domains —
 * covers the most-used services. Refresh periodically by importing the full
 * `disposable_email_blocklist.conf` and re-running this module's tests.
 *
 * Lookup is O(1) via Set. Domains are lowercase, no leading `@`.
 */
const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  '0-mail.com', '027168.com', '0815.ru', '0clickemail.com', '0wnd.net', '0wnd.org',
  '10mail.org', '10minutemail.co.uk', '10minutemail.com', '10minutemail.de',
  '10minutemail.net', '10minutemail.org', '10minutesmail.com', '10minutesmail.net',
  '10x.es', '11mail.com', '12houremail.com', '15qm-mail.red', '15qm.com',
  '1secmail.com', '1secmail.net', '1secmail.org', '20mail.in', '20mail.it',
  '20minutemail.com', '20minutemail.it', '21cn.com', '24hourmail.com',
  '2anom.com', '2prong.com', '30minutemail.com', '33mail.com', '3d-painting.com',
  '4warding.com', '4warding.net', '4warding.org', '60minutemail.com',
  '675hosting.com', '675hosting.net', '675hosting.org', '6paq.com', '7tags.com',
  '99experts.com', 'a-bc.net', 'abusemail.de', 'abyssmail.com', 'acentri.com',
  'advantimo.com', 'afrobacon.com', 'ag.us.to', 'agedmail.com', 'ahk.jp',
  'akapost.com', 'akerd.com', 'akmail.in', 'alivance.com', 'ama-trade.de',
  'amilegit.com', 'amiri.net', 'amiriindustries.com', 'anit.ro', 'anonbox.net',
  'anonmails.de', 'anonymail.dk', 'anonymbox.com', 'antichef.com', 'antichef.net',
  'antispam.de', 'antispammail.de', 'armyspy.com', 'artman-conception.com',
  'asdasd.ru', 'azazazatashkent.tk', 'baxomale.ht.cx', 'beefmilk.com',
  'beerolympics.se', 'big1.us', 'binkmail.com', 'bio-muesli.net', 'bobmail.info',
  'bofthew.com', 'boun.cr', 'bouncr.com', 'breakthru.com', 'brefmail.com',
  'bsnow.net', 'bspamfree.org', 'buffemail.com', 'bugmenot.com', 'bumpymail.com',
  'burnermail.io', 'burstmail.info', 'buyusedlibrarybooks.org', 'byom.de',
  'c2.hu', 'cachedot.net', 'card.zp.ua', 'casualdx.com', 'cek.pm', 'cellurl.com',
  'cetpass.com', 'chacuo.net', 'chammy.info', 'cheatmail.de', 'childsavetrust.org',
  'chogmail.com', 'choicemail1.com', 'clixser.com', 'cmail.club', 'cmail.net',
  'cmail.org', 'consumerriot.com', 'cool.fr.nf', 'correo.blogos.net', 'cosmorph.com',
  'courriel.fr.nf', 'courrieltemporaire.com', 'crapmail.org', 'crazymailing.com',
  'cubiclink.com', 'curryworld.de', 'cust.in', 'cuvox.de', 'd3p.dk',
  'dacoolest.com', 'daintly.com', 'dandikmail.com', 'dayrep.com', 'dbunker.com',
  'dcemail.com', 'deadaddress.com', 'deadspam.com', 'deagot.com', 'dealja.com',
  'delikkt.de', 'despam.it', 'despammed.com', 'devnullmail.com', 'dfgh.net',
  'digitalsanctuary.com', 'dingbone.com', 'discard.email', 'discardmail.com',
  'discardmail.de', 'disposable.com', 'disposable.email', 'disposableaddress.com',
  'disposableemailaddresses.com', 'disposableinbox.com', 'dispose.it',
  'disposeamail.com', 'disposemail.com', 'dispostable.com', 'divermail.com',
  'dm.w3internet.co.uk', 'dodgeit.com', 'dodgit.com', 'dodgit.org',
  'dodsi.com', 'doiea.com', 'domforfb1.tk', 'dontreg.com', 'dontsendmespam.de',
  'dotmsg.com', 'drdrb.com', 'drdrb.net', 'duck2.club', 'dump-email.info',
  'dumpandjunk.com', 'dumpmail.de', 'dumpyemail.com', 'duskmail.com',
  'e-mail.com', 'e-mail.org', 'easytrashmail.com', 'edinburgh-airporthotels.com',
  'einrot.com', 'einrot.de', 'eintagsmail.de', 'email60.com', 'emailgo.de',
  'emailias.com', 'emailigo.de', 'emailinfive.com', 'emaillime.com',
  'emailmiser.com', 'emailondeck.com', 'emailproxsy.com', 'emails.ga',
  'emailsensei.com', 'emailtemporanea.com', 'emailtemporanea.net', 'emailtemporario.com.br',
  'emailthe.net', 'emailtmp.com', 'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emeil.in', 'emeil.ir', 'emeraldwebmail.com', 'emil.com',
  'emkei.cz', 'emz.net', 'enterto.com', 'ephemail.net', 'ero-tube.org',
  'esemay.com', 'evopo.com', 'explodemail.com', 'eyepaste.com', 'fakeinbox.com',
  'fakeinformation.com', 'fakemail.fr', 'fakemailgenerator.com', 'fakemailz.com',
  'fammix.com', 'fansworldwide.de', 'fantasymail.de', 'fast-email.info',
  'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com',
  'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com',
  'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com', 'fightallspam.com',
  'filzmail.com', 'fizmail.com', 'fleckens.hu', 'flemail.ru', 'flurred.com',
  'flyspam.com', 'forgetmail.com', 'fr33mail.info', 'frapmail.com', 'freecat.net',
  'freeletter.me', 'freemail.ms', 'freundin.ru', 'friendlymail.co.uk',
  'fux0ringduh.com', 'fyii.de', 'garliclife.com', 'gehensiemirnichtaufdensack.de',
  'gelitik.in', 'get-mail.cf', 'get-mail.ga', 'get-mail.ml', 'get-mail.tk',
  'get1mail.com', 'get2mail.fr', 'getairmail.com', 'getmails.eu', 'getonemail.com',
  'getonemail.net', 'ghosttexter.de', 'giantmail.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'gmial.com', 'goemailgo.com', 'gotmail.net', 'gotmail.org',
  'gotti.otherinbox.com', 'great-host.in', 'greggamel.com', 'greggamel.net',
  'gregorsky.zone', 'gregorygamel.com', 'gregorygamel.net', 'grr.la', 'gsrv.co.uk',
  'guerillamail.biz', 'guerillamail.com', 'guerillamail.de', 'guerillamail.info',
  'guerillamail.net', 'guerillamail.org', 'guerrillamail.biz', 'guerrillamail.com',
  'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamailblock.com', 'gustr.com', 'h.mintemail.com', 'h8s.org',
  'hacccc.com', 'haltospam.com', 'harakirimail.com', 'hartbot.de', 'hatespam.org',
  'hellodream.mobi', 'herp.in', 'hidemail.de', 'hidzz.com', 'hochsitze.com',
  'hopemail.biz', 'hot-mail.cf', 'hot-mail.ga', 'hot-mail.ml', 'hot-mail.tk',
  'hotpop.com', 'hulapla.de', 'ieatspam.eu', 'ieatspam.info', 'ieh-mail.de',
  'ihateyoualot.info', 'iheartspam.org', 'imails.info', 'imgof.com', 'imgv.de',
  'imstations.com', 'inbax.tk', 'inbox.si', 'inbox2.info', 'inboxalias.com',
  'inboxbear.com', 'inboxclean.com', 'inboxclean.org', 'inboxdesign.me',
  'inboxstore.me', 'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'infocom.zp.ua', 'insorg-mail.info', 'instant-mail.de', 'ip6.li', 'ipoo.org',
  'irish2me.com', 'iwi.net', 'jetable.com', 'jetable.fr.nf', 'jetable.net',
  'jetable.org', 'jnxjn.com', 'jourrapide.com', 'junk1e.com', 'junkmail.com',
  'junkmail.ga', 'junkmail.gq', 'kasmail.com', 'kaspop.com', 'keepmymail.com',
  'killmail.com', 'killmail.net', 'kimsdisk.com', 'kingsq.ga', 'kir.ch.tc',
  'klassmaster.com', 'klassmaster.net', 'klzlk.com', 'kook.ml', 'koszmail.pl',
  'kulturbetrieb.info', 'kurzepost.de', 'l33r.eu', 'labetteraverouge.at',
  'lackmail.net', 'lags.us', 'landmail.co', 'lawlita.com', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com', 'loadby.us',
  'login-email.cf', 'login-email.ga', 'login-email.ml', 'login-email.tk',
  'lol.ovpn.to', 'lookugly.com', 'lortemail.dk', 'lr78.com', 'lroid.com',
  'lukop.dk', 'm21.cc', 'mail-filter.com', 'mail-temporaire.fr', 'mail.by',
  'mail.mezimages.net', 'mail.zp.ua', 'mail1a.de', 'mail21.cc', 'mail2rss.org',
  'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcatch.com', 'mailde.de', 'mailde.info', 'maildrop.cc',
  'maileater.com', 'mailexpire.com', 'mailfa.tk', 'mailforspam.com',
  'mailfreeonline.com', 'mailguard.me', 'mailimate.com', 'mailin8r.com',
  'mailinater.com', 'mailinator.com', 'mailinator.net', 'mailinator.org',
  'mailinator2.com', 'mailincubator.com', 'mailismagic.com', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com', 'mailmoat.com', 'mailms.com', 'mailnator.com',
  'mailnesia.com', 'mailnull.com', 'mailpick.biz', 'mailproxsy.com', 'mailrock.biz',
  'mailscrap.com', 'mailshell.com', 'mailsiphon.com', 'mailslapping.com',
  'mailslite.com', 'mailtemp.info', 'mailtome.de', 'mailtothis.com',
  'mailtrash.net', 'mailtv.net', 'mailtv.tv', 'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'manifestgenerator.com', 'manybrain.com', 'mbx.cc',
  'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'mierdamail.com', 'migumail.com', 'mintemail.com',
  'misterpinball.de', 'mjukglass.nu', 'mobi.web.id', 'moburl.com', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com', 'msa.minsmail.com',
  'mt2009.com', 'mt2014.com', 'mx0.wwwnew.eu', 'my10minutemail.com', 'mycard.net.ua',
  'mycleaninbox.net', 'mymail-in.net', 'mymailoasis.com', 'mynetstore.de',
  'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org', 'myspacepimpedup.com', 'myspamless.com',
  'mytempemail.com', 'mytempmail.com', 'mytrashmail.com', 'nabuma.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net', 'netmails.com',
  'netmails.net', 'netzidiot.de', 'neverbox.com', 'nice-4u.com', 'nincsmail.com',
  'nincsmail.hu', 'nnh.com', 'no-spam.ws', 'noblepioneer.com', 'nomail.pw',
  'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us', 'nospamthanks.info', 'notmailinator.com',
  'nowhere.org', 'nowmymail.com', 'nurfuerspam.de', 'nus.edu.sg', 'objectmail.com',
  'obobbo.com', 'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info',
  'online.ms', 'opayq.com', 'ordinaryamerican.net', 'otherinbox.com', 'ovpn.to',
  'owlpic.com', 'pancakemail.com', 'pcusers.otherinbox.com', 'pjjkp.com',
  'plexolan.de', 'poofy.org', 'pookmail.com', 'privacy.net', 'privatdemail.net',
  'proxymail.eu', 'prtnx.com', 'punkass.com', 'putthisinyourspamdatabase.com',
  'pwrby.com', 'quickinbox.com', 'rcpt.at', 'reallymymail.com', 'realtyalerts.ca',
  'recode.me', 'recursor.net', 'reliable-mail.com', 'rhyta.com', 'rmqkr.net',
  'royal.net', 'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net', 'safersignup.de',
  'safetymail.info', 'safetypost.de', 'saynotospams.com', 'schafmail.de',
  'schrott-email.de', 'secretemail.de', 'secure-mail.biz', 'selfdestructingmail.com',
  'sendspamhere.com', 'sharklasers.com', 'shieldedmail.com', 'shiftmail.com',
  'shitmail.me', 'shitmail.org', 'shitware.nl', 'shmeriously.com', 'shortmail.net',
  'sibmail.com', 'sinnlos-mail.de', 'siteposter.net', 'skeefmail.com', 'slapsfromlastnight.com',
  'slaskpost.se', 'smashmail.de', 'smellfear.com', 'snakemail.com', 'sneakemail.com',
  'sneakmail.de', 'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com',
  'soodonims.com', 'spam.la', 'spam.su', 'spam4.me', 'spamavert.com', 'spambob.com',
  'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de', 'spambog.ru',
  'spambox.us', 'spamcero.com', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamex.com', 'spamfree24.com', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgoes.in',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com',
  'spamobox.com', 'spamoff.de', 'spamslicer.com', 'spamspot.com', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtroll.net', 'speed.1s.fr', 'stinkefinger.net',
  'stop-my-spam.com', 'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info',
  'talkinator.com', 'teewars.org', 'teleworm.com', 'teleworm.us', 'temp-mail.com',
  'temp-mail.org', 'temp-mail.ru', 'tempail.com', 'tempalias.com', 'tempe-mail.com',
  'tempemail.biz', 'tempemail.co.za', 'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempinbox.com', 'tempmail.eu', 'tempmail.it', 'tempmaildemand.com',
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempthe.net', 'thanksnospam.info', 'thankyou2010.com',
  'thc.st', 'thelimestones.com', 'thisisnotmyrealemail.com', 'throam.com',
  'throwawayemailaddress.com', 'tilien.com', 'tittbit.in', 'tizi.com',
  'tmail.ws', 'tmailinator.com', 'toiea.com', 'toomail.biz', 'topranklist.de',
  'tradermail.info', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash2009.com', 'trashdevil.com', 'trashemail.de', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.ws',
  'trashmailer.com', 'trashymail.com', 'trashymail.net', 'trbvm.com', 'trialmail.de',
  'trillianpro.com', 'twinmail.de', 'tyldd.com', 'uggsrock.com', 'umail.net',
  'upliftnow.com', 'uplipht.com', 'uroid.com', 'us.af', 'venompen.com',
  'veryrealemail.com', 'vidchart.com', 'viditag.com', 'viralplays.com',
  'vpn.st', 'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me',
  'weg-werf-email.de', 'wegwerf-email-addressen.de', 'wegwerf-emails.de',
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org', 'wh4f.org',
  'whatiaas.com', 'whatpaas.com', 'whatsaas.com', 'whopy.com', 'whyspam.me',
  'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net', 'www.e4ward.com', 'wwwnew.eu', 'x.ip6.li',
  'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com', 'xoxy.net',
  'yapped.net', 'yeah.net', 'yep.it', 'yogamaven.com', 'yopmail.com',
  'yopmail.fr', 'yopmail.net', 'youmailr.com', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de',
  'zetmail.com', 'zippymail.info', 'zoaxe.com', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'zxcv.com', 'zxcvbnm.com', 'zzz.com',
])

/**
 * Returns true if the email's domain is in the disposable blocklist.
 * Walks dot-segments right-to-left so subdomains of listed entries
 * (e.g. `x@anything.mailinator.com`) also match without a Public-Suffix List.
 * Returns false for malformed input — caller should validate format first.
 */
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf('@')
  if (at < 0 || at === email.length - 1) return false
  const fullDomain = email.slice(at + 1).trim().toLowerCase()
  if (DISPOSABLE_DOMAINS.has(fullDomain)) return true
  let idx = fullDomain.indexOf('.')
  while (idx >= 0 && idx < fullDomain.length - 1) {
    const suffix = fullDomain.slice(idx + 1)
    if (DISPOSABLE_DOMAINS.has(suffix)) return true
    idx = fullDomain.indexOf('.', idx + 1)
  }
  return false
}
